// <auto-generated />
namespace ProjectBurgerMenu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addpropProduct_DealOfTheDay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpropProduct_DealOfTheDay));
        
        string IMigrationMetadata.Id
        {
            get { return "202410181118216_addpropProduct_DealOfTheDay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
